Add auth-via-ssh [#42]

diff --git a/bin/utils/auth-via-ssh b/bin/utils/auth-via-ssh
--- a/bin/utils/auth-via-ssh
+++ b/bin/utils/auth-via-ssh
@@ -1,11 +1,11 @@
 #! /usr/bin/env bash
 ## Usage:
-## echo "<password>" | auth-via-su "<username>"
+## echo "<password>" | RSC_AUTH_SSH_HOST=<hostname> auth-via-ssh "<username>"
 ##
 ## Description:
 ## Validates the password on standard input for the user
 ## specified as the first argument
-## 
+##
 ## Requires:
 ## * expect (https://www.nist.gov/services-resources/software/expect)
 ## * ssh
@@ -13,7 +13,15 @@
 ## Author: Henrik Bengtsson (2021)
 set -o nounset
 
-RSC_AUTH_LOGFILE=${RSC_AUTH_LOGFILE:-${2}}
+if ! command -v expect &> /dev/null; then
+    debug "ERROR: $0 requires 'expect'"
+    echo >&2 "ERROR: $0 requires 'expect'"
+    exit 2
+fi    
+
+RSC_AUTH_SSH_HOST=${RSC_AUTH_SSH_HOST:-${2}}
+
+RSC_AUTH_LOGFILE=${RSC_AUTH_LOGFILE:-${3}}
 
 function debug() {
     if [[ -z ${RSC_AUTH_LOGFILE} ]]; then
@@ -31,25 +39,18 @@ if [[ $# -lt 1 ]]; then
 fi
 RSC_USERNAME="${1}"
 
+
 if [[ "${RSC_USERNAME}" != "${USER}" ]]; then
     debug "Invalid authentication (incorrect username)"
     exit 1
 fi
 
-if command -v expect &> /dev/null; then
-    debug "  Using 'expect' to validate password:"
-    debug "  Reading password from standard input"
+## Read password from standard input
+IFS='' read -r password
 
-    ## Read password from standard input
-    IFS='' read -r password
-
-    ## WORKAROUND: Not all 'su' versions support being called
-    ## from within a script. Because of this, we use expect'
-    ## to trick it, it's doing so.  This workaround was adopted
-    ## from https://stackoverflow.com/a/1503831/1072091
-    command expect <<EOF
-eval spawn su "$USER" -c exit
-expect "Password"
+command expect <<EOF
+eval spawn ssh -o PreferredAuthentications=password -o NumberOfPasswordPrompts=1 -l "$USER" "${RSC_AUTH_SSH_HOST}" "echo true"
+expect "password"
 send "${password}\n"
 set wait_result  [wait]
 ## check if it is an OS error or a return code from our command
@@ -61,12 +62,7 @@ else {
     exit 1 
 }
 EOF
-    valid=$?
-else
-    debug "Using 'su' to validate password"
-    su "$USER" -c exit
-    valid=$?
-fi
+valid=$?
 
 if [[ ! "${valid}" -eq 0 ]]; then
     debug "Invalid authentication (incorrect password)"
